-- phpMyAdmin SQL Dump
-- version 3.5.1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Jan 07, 2013 at 03:15 PM
-- Server version: 5.5.25
-- PHP Version: 5.4.4

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

--
-- Database: `property_cloud`
--

-- --------------------------------------------------------

--
-- Table structure for table `property`
--

CREATE TABLE `property` (
  `property_id` int(11) NOT NULL AUTO_INCREMENT,
  `address` varchar(150) NOT NULL,
  `address_two` varchar(150) NOT NULL,
  `address_three` varchar(150) NOT NULL,
  `county` enum('Antrim','Armagh','Carlow','Cavan','Clare','Cork','Donegal','Down','Dublin','Fermanagh','Galway','Kerry','Kildare','Kilkenny','Laois','Leitrim','Limerick','Derry','Longford','Louth','Mayo','Meath','Monaghan','Offaly','Roscommon','Sligo','Tipperary','Tyrone','Waterford','Westmeath','Wexford','Wicklow') NOT NULL,
  `price` int(50) NOT NULL,
  `rooms` varchar(5) NOT NULL,
  `type` varchar(150) NOT NULL,
  `contact` varchar(50) NOT NULL,
  `phone` varchar(150) NOT NULL,
  `description` varchar(2500) NOT NULL,
  `imagefile` varchar(250) NOT NULL,
  `status` varchar(50) NOT NULL,
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`property_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=148 ;

--
-- Dumping data for table `property`
--

INSERT INTO `property` (`property_id`, `address`, `address_two`, `address_three`, `county`, `price`, `rooms`, `type`, `contact`, `phone`, `description`, `imagefile`, `status`, `updated`) VALUES
(49, '565 Old Park Road', 'City Centre', 'Belfast', 'Antrim', 169823, '3', 'Semi-Detached', 'Shanks and Company', '(028) 9071 3888', 'A deceptively spacious semi detached villa holding a highly sought after main road position within close proximity to schools and local amenties. The property offers well proportioned accommodation and a wealth of noteworthy features and finishes. Early viewing is an absolute must. ', '5.jpg', 'forsale.png', '2012-12-31 11:19:37'),
(50, '8 Squireshill Road', 'Belfast City Centre', 'Belfast', 'Antrim', 219853, '3', 'Detached', 'Shanks and Company', '(028) 9071 3888', 'A most impressive detached bungalow holding an enviable position off the Crumlin Road benefiting from views over Belfast &amp; County Down. This prestigious property offers bright generous accommodation which is further enhanced by a wealth of appealing features and top quality finishes complemented by impeccable presentation throughout. Viewing is an absolute must.', '6.jpg', 'forsale.png', '2012-12-31 13:52:55'),
(51, 'Flat 38', '175 Skegoneill Avenue', 'Belfast', 'Antrim', 519000, '3', 'Apartment', 'Shanks and Company', '(028) 9071 3888', 'Deceptively spacious and extremely well presented first floor apartment 3 bedrooms - lounge Modern fitted kitchen with built n oven and hob White bathroom suite - ceramic tiled floor PVC double glazed windows Phoenix gas central heating Carpets and blinds included in sale Ideal first time purchase Ready for immediate possession', '7.jpg', 'forsale.png', '2012-12-31 14:16:56'),
(52, '29 Silverstream Terrace', 'Belfast City Centre', 'Belfast', 'Antrim', 489000, '2', 'Terraced', 'Shanks and Company', '(028) 9071 3888', 'Well presented semi-detached property 2 bedrooms - 1 reception room Fitted kitchen with cooker and washing machine White bathroom suite Gas fired central heating Garden to front in lawn. Garden to rear in lawn.', '8.jpg', 'forsale.png', '2012-12-31 14:20:30'),
(53, '16 Bells Row Court', 'Lurgan', 'Craigavon', 'Armagh', 79000, '3', 'Terraced', 'Reeds Rains Lisburn', '02892 675321', '16 Bells Row Court, Lurgan, BT67 9 NAWe Advise That An Offer Has Been Made For The Above Property In The Sum Of Â£40,000. Any Persons Wishing To Increase On This Offer Should Notify The agents Of Their Best Offer Prior To Exchange Of Contracts.\r\nReeds Rains14/16 Market Street LisburnBT28 1 ABTel: 02892 675321 Mid Terrace Townhouse On The Periphary Of North Lurgan Town. A Popular And Sought after Residential Location For Its Convenience To The Town Centre, Local Schools and Amenities. An Excellent Public Transport Bus Route Is In Place. Accommadation Comprises Ent Hall, Lounge, Kitchen/Dining, Landing, Three Bedrooms, Bathroom, Rear Enclosed Garden.', '9.jpg', 'forsale.png', '2012-12-31 14:28:41'),
(54, '102 Breezemount', 'Hamiltonsbawn', 'Armagh', 'Armagh', 100000, '3', 'Semi-Detached', 'Reeds Rains Lisburn', '02892 675321', ' Semi detached chalet bungalow located in popular residential development of Hamiltonsbawn. This property offers ideal accommodation for first time buyer looking starter home or family alike. Conveniently located within walking distance of school and shops. Accommodation comprises lounge open plan to dining area. Fitted kitchen/diner. Three well proportioned bedrooms and bathroom. Front garden laid in lawn with tarmac driveway to side. Generous paved rear garden area. It further benefits from oil fired central heating(untested) and double glazing. Early viewing is recommended.   \r\n  ', '10.jpg', 'sold.png', '2012-12-31 14:31:10'),
(55, 'Corcrain Mews', 'Craigavon', 'Armagh', 'Armagh', 80000, '3', 'Detached', 'Reeds Rains Lisburn', '02892 675321', 'Detached Villa In The Popular Reidential Location Of Corcrain Mews. Well Presented This Property Will Appeal To Those Who Require Convenience Living. Various Local Amenities, Excellent Public Transport Services, Schools, Easy Access To Town Centre And M1 Are Only Some Of The Benefits Of This Area. Accommadation Comprises Entrance Hall, Lounge, Kitchen/Dining, Conservatory, Landing, Three Bedrooms, Shower Room. Oil Fired Central Heating, Double Glazing Front and Rear Gardens Compliment This Family Home. Viewing Is Essential To Fully Appreciate.', '11.jpg', 'forsale.png', '2012-12-31 14:36:38'),
(56, '2 Victoria Street', 'Armagh', 'BT61 9DT', 'Armagh', 122000, '1', 'Apartment', 'SmartMove NI ', '028 3752 7230', '1 Bed Apartment For Rent', '12.png', 'forsale.png', '2012-12-31 21:46:54'),
(57, '52 The Laurels', 'Tulllow Road', 'Carlow Town', 'Carlow', 71000, '3', 'Terraced', 'Helen Brophy', '059 9140344', 'This neat mid-terraced home is the ideal starter or investment opportunity, presented for sale in good order throughout and positioned at a very realistic reserve. Accommodation is well proportioned, off street parking and a private rear garden add to its appeal. Viewings are highly recommended.', '13.jpg', 'forsale.png', '2012-12-31 21:51:44'),
(58, 'Hanover Cottage', 'Hanover Rd. Carlow', 'Carlow Town', 'Carlow', 100000, '2', 'Detached', 'Kehoe Auctioneers', 'Kehoe Auctioneers', '2  Storey Traditional cottage with single storey outhouse on site extending to c. 425msq \r\n\r\nHanover Cottage is located on Hanover Rd. in a good residential area of Carlow close to all amenities and to the centre of town. \r\n\r\nThe cottage is suitable for renovation or new build subject to planning permission. The present site presents the gable end to the road with garden area to front of house.', '14.jpg', 'forsale.png', '2012-12-31 21:54:35'),
(62, '10 Rathdale', 'Pollerton', 'Carlow Town', 'Carlow', 142500, '3', 'Semi-Detached', 'James McDermott', '059 9140344', 'This hugely attractive family home commands a prominent site in this exclusive development of 10 only semi-detached homes. Generously proportioned, its unique style and layout ensures maximum privacy while affording space for all family activities. ', '16.jpg', 'forsale.png', '2012-12-31 22:13:21'),
(63, 'Apt 106 Riverdell', 'Centaur Street', 'Carlow Town', 'Carlow', 105000, '2', 'Apartment', 'Carlow Property Management', '059 9135800', 'Bright 2 bedroom apartment in Carlow town centre. Fabulous views over the river Barrow and the Millennium Park. This apartment comprises of a spacious kitchen/living area, a main bathroom with bath, 2 double bedrooms with fitted wardrobes and one en suite with shower. There is also a balcony over looking the park.', '17.jpg', 'forsale.png', '2012-12-31 22:16:05'),
(64, '16 The Oaks', 'Drumgola Wood', 'Cavan', 'Cavan', 170000, '4', 'Detached', 'Declan Woods', '049 4380038', 'Excellent 4 bedroom detached property in quiet end of a cul de sac with private garden to rear, enjoys unspoilt views of Drumgola Lough. ', '18.jpg', 'forsale.png', '2012-12-31 22:18:42'),
(65, 'Lymewood Mews', 'Northwood', 'Santry', 'Dublin', 240000, '2', 'Apartment', 'Laurence Hickey IAVI', '086 380 2161', 'Hickey Group International is delightful to present this spacious contemporary two bed, two bathroom property in the popular Lymewood Mews area of the Northwood developement of Santry Dublin 9. Consisting of all modern conveniences this 3rd floor property is fitted to a high standard and boasts generously proportioned rooms. This block itself is facing the new Northwood shopping complex and the Northwood Gym. Viewing is highly recommended. ', '2.jpg', 'forsale.png', '2013-01-02 14:49:29'),
(66, '10', 'Coldwater Lakes', 'Saggart', 'Dublin', 875000, '4', 'Detached', 'Gary Wildman', '01 835 8833', 'The property offers: A large entrance hall/foyer with staircase to first floor, a large fully fitted kitchen with dinning area, a family room and also a large sitting room and drwaing room. There is two toilets, a utility room and attached to the property is a double garage.', '3.jpg', 'forsale.png', '2013-01-02 15:12:05'),
(67, '4 Oak View', 'Santry', 'Dublin 9', 'Dublin', 169000, '3', 'Semi-Detached', 'Ronan Crinion', '01 8867090', '    \n  Situated close to Omni Park Shopping Centre and Beaumont Hospital with bus routes, schools and may other local amenities nearby this wonderful opportunity should simply not be missed. The property has a hallway, living room, fitted kitchen, with spacious breakfast room on the ground floor. Upstairs there are three bedrooms and a large family bathroom. Overlooking a shared parkland to the front &amp; a low maintenance west facing garden to the rear and access at the side and viewing is highly recommended to appreciate all this gem has to offer. ', '20.jpg', 'forsale.png', '2013-01-02 15:18:12'),
(68, 'Apt. 19', 'Stewart Hall', 'Ryders Row', 'Dublin', 75000, '1', 'Apartment', 'Brian Caulfield MIPAV', '8870613', '', '22.jpg', 'forsale.png', '2013-01-02 15:26:01'),
(69, 'Crumlin Road', 'Crumlin', 'Dublin 12', 'Dublin', 175000, '3', 'Terraced', 'Ciara', '01 8870613', 'Clement Herron Real Estate are pleased to welcome to the market this well maintained four bed mid terraced town house in the centre of Crumlin. ', '23.jpg', 'forsale.png', '2013-01-02 15:27:36'),
(70, '3 Edenbrook Court', ' Rathfarnham', 'Dublin 14', 'Dublin', 269950, '3', 'Terraced', 'Castle Estate Agents', '01 8870613', 'Castle Estates are delighted to bring this charming 3 bed mid terrace house to the market. Situated in this highly coveted location, the property boasts 2 double (one en suite) and one single bedroom. On the ground floor there is a fitted kitchen and separate living room. South facing, 3 Edenbrook court benefits from mature landscaped gardens and parking to the front.', '2e5c93fc5fcb277c88837e18ff8cc0456f338a0df1fdbab76cd646d5bf875fd9.jpg', 'forsale.png', '2013-01-02 15:29:21'),
(71, '7 Hazelwood Park', 'Artane', 'Dublin 5', 'Dublin', 249000, '3', 'Semi-Detached', 'Anne Da Silva', '01 8870613', 'This generous versatile house is ideal for family living with west facing garden, side access, mature residential setting in a most convenient location close to a selection of schools, bus services and an excellent variety of shops. The site offers the purchaser an opportunity to enlarge the property (subject to any necessary planning permission) and still retain the original gardens and side entrance. ', '24.jpg', 'forsale.png', '2013-01-02 15:30:42'),
(72, '18 Royse Road', 'Phibsborough', 'Dublin 7', 'Dublin', 160000, '5', 'Terraced', 'Brian Caulfield MIPAV', '01 8870613', '', '25.jpg', 'forsale.png', '2013-01-02 19:37:55'),
(74, 'Ile De Cerf', 'Ballykea Cross', 'Loughshinny', 'Dublin', 380000, '5', 'Detached', 'Brian Caulfield MIPAV', '01 8870613', 'Large spacious c.180 sq.m detached house on c.3/4 acre site in popular location in Loughshinny. This property would make a good family home and is ideally located within walking distance of local primary school and community centre. The beautiful beach and harbour that Loughshinny has to offer not to mention its cliffside walks are only c.5 minutes walk away. The amenities of Skerries and Rush are only 5 minutes drive away. The M1, M50 &amp; Airport are all within a 15-25 minute drive. ', '26.jpg', 'forsale.png', '2013-01-02 19:44:20'),
(75, '83 Claremont Court', 'Glasnevin', 'Dublin 9', 'Dublin', 240000, '8', 'Semi-Detached', 'Brian Caulfield MIPAV', '01 8870613', 'Priced to sell, this eight bedroom House, is a perfect starter home for discerning first time buyers, or as an investment property for astute investor. \r\nClose to all amenities, shops and public transport. \r\nFurther details can be had on request ', '29.jpg', 'forsale.png', '2013-01-02 19:46:32'),
(76, 'The Hills', '126 Rochestown Avenue', 'Dun Laoghaire', 'Dublin', 525000, '5', 'Detached', 'Darragh Brady', '+353 (0) 1 288 5011', 'Savills is delighted to present The Hills, 126 Rochestown Avenue, Dun Laoghaire, Co. Dublin to the market. This spacious 5 bed detached family home (1,765 Sqft / 164 Sqm excluding the garage) will appeal to a wide audience and is ideal for a family looking for a home to modernise/develop and make their own. No.126 is set back from the road and benefits from generous off street parking and garage for additional storage. ', '30.jpg', 'forsale.png', '2013-01-02 19:48:21'),
(77, '13 Saggart Lakes', 'Saggart', 'Saggart', 'Dublin', 900000, '6', 'Detached', 'Karl Hannigan', '+353 (0) 1 288 5011', 'This stunning detached property, on circa 1 acre of matured landscaped garden, with electronic gates and cobbled driveway, is now available to the discerning buyer. With over 4,200 sq.ft., of spacious rooms, this 3 story detached house consists of 6 Bedroom, four of which are en-suite, main bathroom, sun balconies, reception rooms, large bespoke kitchen and a garage which has been converted for use as a gymnasium or other such function. ', '31.jpg', 'forsale.png', '2013-01-02 19:50:33'),
(79, '80 Grattan Lodge', 'Donaghmede', 'Dublin 13', 'Dublin', 349000, '5', 'Semi-Detached', 'Alison Cooney', '01 8272300', 'This large spacious 4/5 Bedroom Semi-detached family home has been newly redecorated and carpeted throughout and is presented in superb decorative order offering bright, spacious and well appointed accommodation throughout. The Property has the added benefit of a small conservatory to the rear which enhances and extends this beautiful home. ', '33.jpg', 'forsale.png', '2013-01-02 19:54:48'),
(80, 'Caheraderry', 'Lahinch', 'Clare', 'Clare', 185000, '3', 'Detached', 'Derek MacDonough', '089484442333', 'A three bedroom bungalow on circa half acre site in a quiet and rural area approx. 3 miles from Lahinch, Liscannor and Ennistymon. Short drive to Lisdoonvarna, Doolin and the Cliffs of Moher. Within earshot of Atlantic ocean with sea views of Lahinch.\r\n20 year old with one resident owner. Duel heating. o.f.c.h. with solid fuel option. Also solid fuel stove in large sitting room.', '34.jpg', 'forsale.png', '2013-01-02 20:00:07'),
(81, '36', 'Mcnamara Park', 'Ennis', 'Clare', 95000, '3', 'Terraced', 'Kieran', '065 68 67 866', 'A 3 Bedroomed mid terraced town house situated just 2 minutes walk to the town centre. The property has the benefit of a two storey extension (diningroom ground floor and bedroom on the first floor). Features include double glazed windows and doors, oil fired central heating, 3 bedrooms and newly redecorated shower room on ground floor. There is also a large lawn to the rear. Viewing comes highly recommended. c. 74.41 sqm (800 sq ft) approx. BER E2 ', '35.jpg', 'forsale.png', '2013-01-02 20:02:22'),
(82, '5', 'Cul Na Coille', 'Ennis', 'Clare', 215000, '5', 'Detached', 'Diarmuid McMahon', '0876298726', 'Cul-Na Coille is an eye-catching development of only seven stylish, \r\nexecutive, contemporary detached homes. This property is unfinished \r\ninternally!', '36.jpg', 'forsale.png', '2013-01-02 20:04:22'),
(83, 'No. 6 The Mount', 'Ballycorick', 'Ballynacally', 'Clare', 50000, '3', 'Detached', 'REA Paddy Browne', '(065) 6841755', 'Set in a small development of six semi detached houses just off the Ennis to Kildysart Road, close to Ballycorick Church and the village of Ballynacally, and less than a fifteen minute drive to Ennis.', '37.jpg', 'forsale.png', '2013-01-02 20:06:23'),
(84, '3', 'Dun Orga', 'Dunmanway', 'Cork', 160000, '5', 'Detached', 'Daniel Lehane MIPAV', '023 8845481', 'This generously proportioned 5 bedroom house was only recently built and incorporates 1,800 sq. ft of bright and spacious accommodation. The house is completed to a standard builders finish leaving the rest of the fittings and decorating to the lucky purchaser. There is generous garden space with this house with cut stone pillars and walls to the front. Dun Orga itself is a completed estate with only 36 houses in total, 10 of which are similar detached properties.', '38.jpg', 'forsale.png', '2013-01-02 20:08:51'),
(85, '3 Exham Place', 'Margaret Street', 'Cork City Centre', 'Cork', 159000, '3', 'Terraced', 'Sales', '021 4277717', 'An attractive 3 bedroom mid terrace property a mere 5 minute walk from Patrick Street. No 3 is finished and fitted to a high standard and boasts many fine features including a lovely rear yard. ', '39.jpg', 'forsale.png', '2013-01-02 20:12:50'),
(86, '2 The Mills', 'Lower John Street', 'Cork City Centre', 'Cork', 92500, '2', 'Apartment', 'Peter Skuse', '021 4279179', 'Exceptional two bedroom first floor apartment, with one private parking space, located within 3 minutes walk of the city centre. Professional Persons, Merchants, Traders all in the city centre may find this an interesting opportunity due to its most convenient location. Investment property does not come more suitably convenient with parking. Viewing strictly by appointment with sole agents. ', '40.jpg', 'forsale.png', '2013-01-02 20:14:31'),
(87, '18 Dun Laoi', 'Union Quay', 'Cork City Centre', 'Cork', 140000, '2', 'Apartment', 'Peter Skuse', '021 4279179', '2 bedroom first floor apartment with a superb South facing rear aspect. The property would ideally suit an investor, with current tenants in situ and an existing rent roll. \r\nThe accommodation consists of ; Reception Hallway, Superb Large Open Plan Kitchen / Dining / Living Area, Two Spacious Bedrooms and a large bathroom. ', '41.jpg', 'forsale.png', '2013-01-02 20:15:54'),
(88, 'Rockboro Road', 'Old Blackrock Road', 'Cork City Centre', 'Cork', 295000, '4', 'Semi-Detached', 'Alan Burke', '021 4279179', 'This is a beautiful three storey, four bedroom period style property ideally located adjacent to the city centre and yet enjoying parking and plenty of space and privacy with well proportioned accommodation coupled with a gorgeous rear garden that extends over 100ft. The property has been carefully maintained by the current owners and yet there is room for the purchaser to put their own stamp on the property. ', '42.jpg', 'forsale.png', '2013-01-02 20:18:18'),
(89, '1 Portmore Road', 'Portstewart', 'Portstewart', 'Derry', 43000, '3', 'Apartment', 'Craig Wallace', '021 4279179', 'Ground floor duplex apartment comprising 2 bedrooms, open plan kitchen, dining &amp; living area and private balcony. \r\nEconomy 7 heating system. \r\nDouble glazing in uPVC frames. \r\nPrivate balcony with excellent sea views. \r\nCentral location convenient to town centre and promenade area.', '43.jpg', 'forsale.png', '2013-01-02 20:20:08'),
(90, '35', 'Fairfield Road', 'Portstewart', 'Derry', 147000, '3', 'Semi-Detached', 'Craig Wallace', '021 4279179', '3 bedrooms (1 with en-suite), dining kitchen, lounge with open fire, bathroom and cloakroom. \r\nOil fired central heating system. \r\nDouble glazing in uPVC frames. \r\nFully enclosed garden ion lawn and gravel areas to rear. \r\nStone driveway to front with parking for 2 cars. \r\nExterior lighting and water supply.', '44.jpg', 'forsale.png', '2013-01-02 20:21:32'),
(91, '74 ', 'Broomhill Park', 'Coleraine', 'Derry', 245000, '5', 'Detached', 'Amanda or Stacey44', '021 4279179', 'This is by far one of the most attractive detached properties that we have brought to the open market in this area for some period of time. \r\nThe home offers excellent family accommodation and is presented to an extremely high standard which is likely to appeal to all who take time to view.', '45.jpg', 'forsale.png', '2013-01-02 20:23:32'),
(92, '131', 'Leckagh Drive', 'Magherafelt', 'Derry', 73800, '3', 'Terraced', 'Amanda or Stacey44', '021 4279179', 'Three Bedroom Mid-Terrace House, Oil Fired Central Heating - New boiler installed (1 year old).', '46.jpg', 'forsale.png', '2013-01-02 20:26:02'),
(93, 'Ardfarn', 'Bundoran', 'Bundoran', 'Donegal', 70000, '4', 'Detached', 'Declan McLoughlin', '086 8040189', 'Enjoying a rural ambience amidst a picturesque countryside, within easy walking distance of the glorious Lough Melvin and yet within a short drive of Kinlough Village and the towns of Ballyshannon and Bundoran in South County Donegal, this is a substantial two storey detached house with a floor area of circa 215 sq mts (c. 2,323 sq ft).', '47.jpg', 'forsale.png', '2013-01-02 20:27:45'),
(95, '72 Beinn Aoibhinn', 'Gortlee', 'Letterkenny', 'Donegal', 142000, '4', 'Semi-Detached', 'Franklins ', '074 9188000', 'Beautifully maintained throughout, an integral garage could add extra living accommodation if required. The rear garden is well enclosed and does not overlook other houses. Viewing strongly recommended. ', '50.jpg', 'forsale.png', '2013-01-02 20:40:45'),
(96, '37', 'Atlantic Point', 'Bundoran', 'Donegal', 50000, '2', 'Apartment', 'REA McElhinney ', '071 9841261', 'Sea Front spacious 2 bedroom apt, with ensuite and seperate bathroom\r\nPanoramic Sea Views from the living area and kitchen \r\nFEATURES\r\nSea Front AptsSpacious interiorFully furnishedPotential for holiday rent\r\nAccomodation\r\nSitting/Dining Area with combined fitted kitchen\r\nSeperate Bathroom \r\nBedroom 1 with en-suite WC WHB and Electric Shower\r\nBedroom 2\r\nBathroom, Bath, WC and Whb', '51.jpg', 'forsale.png', '2013-01-02 20:43:13'),
(97, '2', 'Woodview Terrace', 'Stranorlar', 'Donegal', 79000, '4', 'Terraced', 'Henry Kee', '071 9841261', 'For sale by private treaty is the above mid-terrace townhouse situated in a prime location and surrounded by all local amenities. The property has undergone major renovation over the years and has been rewired, reroofed and insulated, had oil fired central heating and PVC double glazed windows fitted.', '52.jpg', 'forsale.png', '2013-01-02 20:45:41'),
(98, '8', 'Ashleigh Meadows', 'Rathfriland', 'Down', 146000, '4', 'Detached', 'Louise Carragher53', '071 9841261', 'FOUR BEDROOM DETACHED CHALET HOME WITH ENCLOSED REAR GARDEN', '53.jpg', 'forsale.png', '2013-01-02 20:49:16'),
(99, '12 Delamont Park', 'Upper', 'Knock', 'Down', 147000, '3', 'Semi-Detached', 'Jeff McFerran', '028 90702999', 'This attractive semi detached home offers well proportioned family accommodation within a highly desirable residential location of South East Belfast. Situated within a quiet cul-de-sac just off the Upper Knockbreda Road it is close to many leading schools, local shops, Forestside Shopping Centre, Metro bus links, the George Best City Airport, Holywood Exchange and offers a straightforward commute to Belfast city centre. ', '70.jpg', 'forsale.png', '2013-01-03 11:40:40'),
(100, '20', 'Cline Road', 'Banbridge', 'Down', 80000, '3', 'Terraced', 'Shooter Property Services Banbridge', '028 90702999', '  Beautifully presented throughout and featuring a large Kitchen/Dining and a recently refurbished shower room this attractive 3 bedroom property will please most and is very suited for a first time buyer, young family or property investor. A short distance from the town centre and local schools and appointment to view is highly recommended.', '71.jpg', 'forsale.png', '2013-01-03 11:42:41'),
(101, 'E5 Portora Wharf', 'Queen Street', 'Enniskillen', 'Fermanagh', 245000, '2', 'Apartment', 'Ronnie Kilfeder', '028 6632 4485', 'This is an exceptionally well appointed waterfront apartment located in the prestigious Portora Wharf complex in the heart of Enniskillen town, within walking distance of restaurants and shopping precinct. \r\n\r\nThe Penthouse apartment enjoys unparallel views over the Erne Waterway stretching up to the Round  amenity area and Portora Royal School.', '73.png', 'forsale.png', '2013-01-03 11:48:29'),
(102, '32', 'Birch Grove', 'Teemore', 'Fermanagh', 98000, '3', 'Terraced', 'Ronnie Kilfeder', '028 6632 4485', 'Fine spacious three bedroom house in popular residential area about four miles from the towns of Belturbet or Derrylin.', '74.jpg', 'forsale.png', '2013-01-03 11:50:08'),
(103, '3', 'Lismonaghan Park', 'Kinawley', 'Fermanagh', 147000, '4', 'Detached', 'Rosemary Fleming', '028 8225 0040', 'We offer for sale this attractive 4 bed detached house with a detached garage situated in a popular residential area in the village of Kinawley. This spacious and modern property is located conveniently to all local amenities. It would undoubtedly make an ideal family home.', '75.jpg', 'forsale.png', '2013-01-03 11:52:55'),
(104, '3', 'Lismonaghan Park', 'Kinawley', 'Fermanagh', 147000, '4', 'Detached', 'Rosemary Fleming', '028 8225 0040', '  			We offer for sale this attractive 4 bed detached house with a detached garage situated in a popular residential area in the village of Kinawley. This spacious and modern property is located conveniently to all local amenities. It would undoubtedly make an ideal family home.  			', '76.jpg', 'forsale.png', '2013-01-03 11:56:01'),
(105, '53', 'Fortview Park', 'Kesh', 'Fermanagh', 104700, '3', 'Detached', 'Rosemary Fleming', '028 8225 0040', 'IMMACULATE 3 BEDROOM SEMI-DETACHED CHALET BUNGALOW \r\n\r\nThis property offers a well appointed, tasteful interior and low maintenance exterior at a realistic price. Keen interest is anticipated so contact us now to avoid disappointment. \r\n\r\nAccommodation Details:- \r\n\r\nEntrance Hall: PVC Front Door. Laminate floor. Understair cupboard. Separate Whb/Wc compartment with part tiled walls and tiled floor.', '77.jpg', 'forsale.png', '2013-01-03 11:59:23'),
(106, '55', 'Parklands', 'Athenry', 'Galway', 50000, '3', 'Semi-Detached', 'Brian Sweeney', '091844126', 'Frank Sweeney &amp; Co are pleased to offer this 3 bedroom semi-detached property at Parklands, Athenry, Co.Galway.The property has been empty for some time and is in need of renovation but represents a great investment opportunity for someone to renovate for investment purposes or to live in themselves. ', '78.jpg', 'forsale.png', '2013-01-03 12:02:56'),
(107, '10', 'Cartur Mor', 'Knocknacarra', 'Galway', 170000, '3', 'Semi-Detached', 'John Quinn', '091844126', 'No. 10, Cartur Mor is an absolute gem, really beautiful and ready to walk straight into, being in pristine condition throughout. Gas central heating, double glazing, en-suite off master bedroom, superb flooring and carpets, pristine decorative order, gorgeous gardens to rear, fabulous kitchen fully fitted to include hob, oven, fridge freezer, patio doors off dining area to gardens, excellent utility area and downstairs w.c. and w.h.b. superb tiling in kitchen and bathroom areas. ', '79.jpg', 'forsale.png', '2013-01-03 12:05:22'),
(108, 'Carraig Palmer', 'Quincentinial Drive', 'Salthill', 'Galway', 125000, '2', 'Apartment', 'Maureen McKeown', '091 861000', 'Two, double bedroom 1st floor apartment with spectacular views of Galway Bay. Located on Quincentinial Drive a quiet lane behind The Aquarium.', '82.jpg', 'forsale.png', '2013-01-03 12:14:36'),
(109, '10', 'The Orchard', 'Gort', 'Galway', 95000, '3', 'Semi-Detached', 'Michael Cunningham Auctioneers ', '091 861000', 'This beautifully decorated 3 Bedroom semi detached 1100 sq ft is located a few minutes walk from The Square in Gort.  This property is in turnkey condition and would be ideal as a family home or as an investment, furniture may be purchased also. ', '83.jpg', 'forsale.png', '2013-01-03 12:16:45'),
(110, 'Belmont', 'Clohgans Hill', 'Milltown', 'Galway', 80000, '3', 'Detached', 'Ivan Connaughton Auctioneers', '090666 3700', 'Very attractive three bedroom residence finished to a high standard by its present owners located c. 2 miles from Milltown Village, on the Galway, Mayo border. The residence stands on c. 0.5 acres and has a large garage/workshop to rear. Accommodation includes reception hallway, sitting room, living room, kitchen, bedrooms 3 in all and bathroom. 	', '86.jpg', 'forsale.png', '2013-01-03 12:21:58'),
(111, 'Thrumnasrah', 'Moycullen', 'Galway', 'Galway', 3950000, '4', 'Detached', 'Dooley Auctioneers', '091 556868', 'Seldom does the opportunity arise to acquire a substantial family residence 2,750 sq.ft which combines the very best of both worlds, offering a stunning countryside setting yet only a stones throw from Moycullen village and a mere 5.5 miles to Galway City. This is undoubtedly one of the finest properties on the property market with breathtaking views of the mature gardens and country vistas.   			', '87.jpg', 'forsale.png', '2013-01-03 12:24:57'),
(112, 'Laharn South', 'Caherciveen', 'Kerry', 'Kerry', 235000, '5', 'Detached', 'James Hillis', '066 9473016', 'Luxury, detached dormer bungalow with sea views. A 5 bedroom property, offering spacious accommodation and sitting on approximately half an acre. Only a short drive from Caherciveen and Waterville. This property is recently constructed and comes with Solid Oak flooring throughout, Solid Oak kitchen, painted and decorated to a very high standard. It also benefits from double glazing and oil fired central heating. This property is being offered fully furnished. ', '88.jpg', 'forsale.png', '2013-01-03 12:29:24'),
(113, '56', 'Hawthorne Avenue', 'Killarney', 'Kerry', 170000, '3', 'Semi-Detached', 'Ted Healy', ' 064 6639000', 'Superbly maintained 3 bedroom semi detached property. \r\nSituated within walking distance of Killarney Town \r\nCul de sac location in Hawthorne Avenue \r\nNot overlooked ', '90.jpg', 'forsale.png', '2013-01-03 12:35:39'),
(114, '3', 'Fail Hill', 'Killarney', 'Kerry', 150000, '4', 'Terraced', 'Ted Healy', ' 064 6639000', 'Four bedroom townhouse located in the heart of Killarney. Opposite Killarney Outlet Centre and next to Friary Church. It is within walking distance to the bus and train stations. This property is located in the heart of Killarney Town, across from Killarney Outlet Centre and next to the Friary Church.', '91.jpg', 'forsale.png', '2013-01-03 12:37:59'),
(115, '9 Bishops Court', 'New Street', 'Killarney', 'Kerry', 78000, '2', 'Apartment', 'Ted Healy', ' 064 6639000', 'Second floor apartment, comprising two large bedrooms. The town centre property is in good decorative order throughout and is fully furnished. \r\n\r\nWould be ideal for First time buyer, investor, in good letting area. \r\n\r\nThe property has high ceilings, Gold Shield Electric Heating and Intercom. ', '93.jpg', 'sold.png', '2013-01-03 12:40:41'),
(116, 'Ryston View', 'Newbridge', 'Kildare', 'Kildare', 150000, '2', 'Apartment', 'Alan Nolan', '045 438808', 'Luxurious spacious ground floor apartment within an exclusive development of only 24 Apts. Accommodation includes: kitchen living room, 2 double bedrooms, ensuite, main bathroom, hot press and storage press. Features include: electric security gates with intercom system, alarm, underground car parking space, large patio area, communal satellite dish, granite worktop, TV &amp; phone points, landscaped private grounds and much more. ', '94.jpg', 'forsale.png', '2013-01-03 12:43:09'),
(117, '56 ', 'Straffan Gate', 'Straffan', 'Kildare', 285000, '4', 'Semi-Detached', 'Alan Nolan', '045 438808', 'Spectacular 4 bedroom semi detached family residence located in an upmarket development in a superb location in the aware winning Straffan Village. Property has high specification throughout with a host of outstanding features and hardwood double glazed windows and doors. Property has tobermore paving to front drive with gardens front and rear', '96.jpg', 'sold.png', '2013-01-03 12:46:22'),
(118, 'Butterfly Cottage', 'Churchtown', 'Athy', 'Kildare', 138500, '3', 'Detached', 'Charlie McDermott', '045 438808', 'New to the market is this well presented detached bungalow on a large site in a quiet but convenient location. The property is within a short walk of the local Primary School and is within easy reach of all the amenities that Athy has to offer including shops, leisure facilities and public transport.', '98.jpg', 'forsale.png', '2013-01-03 12:49:08'),
(119, '15', 'Duke St', 'Athy', 'Kildare', 175000, '3', 'Terraced', 'Michael Connaughton', '059 8632815', 'High profile commercial unit with excellent window frontage superbly located in the heart of Athy town. This property is a three storey building benefiting from a yard to rear with side access from the main street. The property enjoys high volumes of passing trade with good parking in the immediate vicinity. ', '100.jpg', 'forsale.png', '2013-01-03 12:52:29'),
(120, '28', 'Oaklawns', 'Paulstown', 'Kilkenny', 95000, '4', 'Terraced', 'Ciaran DNG', '056 7786000', 'Excellent opportunity to purchase a four bed mid terrace property situated in the heart of the village of Paulstown with ease of access to the M9 making commuting very attractive. The property offers well proportioned accommodation and has a good rear garden with a sunny aspect. There is also an entrance to the rear garden from the rear of the property. This property is exceptional value for money and must be seen to be appreciated. ', '101.jpg', 'sold.png', '2013-01-03 12:54:36'),
(121, 'The Parochial House', 'Kilkenny Street', 'Castlecomer', 'Kilkenny', 170000, '4', 'Detached', 'John Buggy', '056 7786000', 'Buggy Auctioneers are delighted to present to the market a wonderful opportunity to acquire a home for life in the heart of Castlecomer. \r\n\r\nWell proportioned living accommodation and 4 exceptional bedrooms combine in this property that offers great potential to the discerning purchaser. Along with 11ft ceilings and cornicing throughout it could become one of the most exceptional homes in the town. \r\n', '102.jpg', 'sold.png', '2013-01-03 12:56:07'),
(122, '38', 'Talbots Gate', 'Freshford Road', 'Kilkenny', 85000, '1', 'Apartment', 'Fran Grincell Properties ', '087 853 1850101', 'Exceptionally well maintained property throughout. Wonderful Investment Opportunity. ', '101.jpg', 'forsale.png', '2013-01-06 18:43:32'),
(123, '10', 'Kylemore Walk', 'Fiddown', 'Kilkenny', 100000, '3', 'Apartment', 'Fran Grincell Properties ', '087 853 1850101', 'This property comprises a three bed semi detached residence located in a small development of 37 quality homes. The property is in good repair throughout with oil fired central heating, fitted kitchen with appliances, open plan kitchen/dining room, garden to the rear with side access and ensuite master bedroom. The property is the last in a row of semi detached houses and enjoys a private position within the estate. 102', '102.jpg', 'forsale.png', '2013-01-06 18:46:16'),
(124, '43', 'Ashwoode Walk', 'Portlaoise', 'Laois', 155000, '4', 'Semi-Detached', 'Caroline Larkin', '(057) 8681111', 'Hume auctioneers are proud to confirm we are retained agents for ashwoode walk \r\nstunning b1 rated homes with an array of amazing features \r\n\r\nmassive specification \r\n\r\nfull details to be added tomorrow \r\n\r\ncall today for viewing.', '103.jpg', 'forsale.png', '2013-01-06 18:48:44'),
(125, '12', 'Ashbury', 'Portlaoise', 'Laois', 150000, '3', 'Terraced', 'Caroline Larkin', '(057) 8681111', 'ONCE AGAIN HUME AUCTIONEERS BRING ANOTHER DISTINGUISHED PORTLAOISE PROPERTY TO THE MARKET \r\nASHBURY: A HIGHLY SOUGHT AFTER LOCATION', '104.jpg', 'forsale.png', '2013-01-06 18:50:37'),
(126, '43', 'Ashwoode Walk', 'Portlaoise', 'Laois', 155000, '4', 'Semi-Detached', 'Caroline Larkin', '(057) 8681111', 'Hume auctioneers are proud to confirm we are retained agents for ashwoode walk \r\nstunning b1 rated homes with an array of amazing features \r\n\r\nmassive specification \r\n\r\nfull details to be added tomorrow \r\n\r\ncall today for viewing.', '103.jpg', 'forsale.png', '2013-01-06 18:52:45'),
(127, 'Doolough', 'Portarlington', 'Laois', 'Laois', 90000, '2', 'Detached', 'Paul Gaynor', '057 86 78080', 'Delightfully large 2 bed cottage on 0.75 acres close to Emo Court. The property comprises of a 105 sq m (1,130 sq ft) cottage, within which you have two bedrooms, sitting room, conservatory, reception room, kitchen, bathroom, hall and toilet. There are additional buildings with this property. The central heating is oil fired and water supply is coming from a local group scheme. The property is a must to view!!! ', '106.jpg', 'forsale.png', '2013-01-06 18:54:39'),
(128, '26', 'Grace Court', 'Dromod', 'Leitrim', 59000, '2', 'Semi-Detached', 'Abbey Property Sales', '071 9651734', 'The lovely fully furnished 2 bed home comes to the market and is priced for a quick sale. The property is situated close to the Railway station on the Mohill road and beside the Copper still Bar and Restaurant. The property is in really good condition and will make a really nice home in the lovely Shannonside village of Dromod.', '107.jpg', 'forsale.png', '2013-01-06 18:57:09'),
(129, 'Gubbs', 'Camber', 'Cloone', 'Leitrim', 124950, '3', 'Semi-Detached', 'Abbey Property Sales', '071 9651734', 'We are pleased to bring to the market this lovely property situated \r\nin a rural setting within easy access to Mohill , Carrick on \r\nShannon and Longford. The property is approached through wooden \r\nentrance gates, has a cattle grid and wooden fencing. The site is \r\napprox 0.75 of an acre surrounded by lovely countryside. A concrete \r\ndriveway surrounds the house with gardens to the front and rear. A \r\nsolid wooden front door leads to a bright and spacious house with \r\nhallway affording ample room for a stairway to the loft area in \r\nwhich additional bedrooms could be added by the new owners. From \r\nthe tiled entrance hall there is a bright sitting room with two \r\nwindows and patio doors.', '108.jpg', 'forsale.png', '2013-01-06 18:58:31'),
(131, 'Tobernea', 'Effin', 'Limerick', 'Limerick', 220000, '', 'Detached', 'Ted Sheehan', '+353(0)63 89277', 'This is a 2 storey detached property of circa 2000 sq. ft. and standing on c. 0.5 acre with magnificent views of the surrounding countryside. The property is situated approximately 2 miles from Charleville and has a tarmacadam driveway with lawns front and rear and mature hedging.', '110.jpg', 'forsale.png', '2013-01-06 20:16:15'),
(132, '18', 'Ferndale', 'Newcastle West', 'Limerick', 159000, '4', 'Semi-Detached', 'Charles OBrien', '069 79931', 'Stunning 4 bedroom semi detached home with large rear extension situated in the Ferndale estate and only a few minutes drive from Newcastle West town centre. This McEnery development is attractively landscaped and maintained to a high standard.', '113.jpg', 'forsale.png', '2013-01-06 20:22:22'),
(133, '23 Markievicz Drive', 'Kincora Park', 'Limerick City', 'Limerick', 55000, '3', 'Terraced', 'JoeWheeler', '069 79931', '3 Bed End of Terrace Residence Features Include: \r\nGas Central Heating with Condenser Boiler \r\nFully Insulated \r\nDouble Glazed Windows Throughout \r\nSouth West Facing Garden ', '114.jpg', 'forsale.png', '2013-01-06 20:24:15'),
(134, '16', 'Newtown Mews', 'Annacotty', 'Limerick', 125000, '3', 'Apartment', 'JC Gubbins', '061 59 00 00', 'A beautiful 3 bedroom duplex located in the prestigious development of Newtown Mews in Annacotty. This property will appeal to both investors and owner occupiers alike. it has wonderful bright rooms and plenty of space throughout', '116.jpg', 'forsale.png', '2013-01-06 20:28:07'),
(135, 'Camlin Willows', 'Cloncoose', 'Longford Town', 'Longford', 285000, '5', 'Detached', 'Frank Regan', '043 335 0000', '', '117.jpg', 'forsale.png', '2013-01-06 20:32:33'),
(136, '22 The Quays', 'Harbour Point', 'Longford Town', 'Longford', 75000, '2', 'Apartment', 'Frank Regan', '043 335 0000', 'Superb modern and spacious two bedroom penthouse apartment for sale in the heart of Longford town,close to all amenities. 2 Bedrooms (2 double, Master bedroom includes en suite), 1 Bathroom, Entrance Hallway,Hot Press,storage Cupboard,Open plan kitchen  dining living room (including Leather suite). ', '118.jpg', 'forsale.png', '2013-01-06 20:36:10'),
(137, '11', 'Sliabh Cairbe', 'Drumlish', 'Longford', 77500, '4', 'Semi-Detached', 'Padraic Davis', '043 335 0000', 'Excellent 4 bedroom semi-detached home in a quiet estate just a stroll from the centre of Drumlish village. This house is completely furnished to a high standard and ready to move into. Will be sold as seen in mint condition! Located on the Drumlish.', '119.jpg', 'forsale.png', '2013-01-06 20:38:31'),
(138, '10', 'Springlawn', 'Longford Town', 'Longford', 130000, '3', 'Semi-Detached', 'Frank Regan', '043 335 0000', '', '120.jpg', 'forsale.png', '2013-01-06 20:41:50'),
(139, '19 Cornmill', 'Hale Street', 'Ardee', 'Louth', 139000, '3', 'Terraced', 'Colin Gallagher', '041 6857637', 'Large mid-terraced 3 bedroom home exceptional town centre location, presented in truly walk-in condition with superb finishes and features both inside and out. Not overlooked to the rear, the rear garden with stone walls offers a sunny retreat. ', '121.jpg', 'forsale.png', '2013-01-06 20:45:12'),
(140, 'Park Avenue', 'Grange Rath', 'Drogheda', 'Louth', 139000, '4', 'Detached', 'Brian McGuirk', '041 6857637', 'Space, comfort and a friendly neighbourhood set the tone for this detached family home. Situated in an unfrequented cul-de-sac in this quality development on the southside of Drogheda, No 21 Park Avenue is ideally located within a short drive of Drogheda train station 20 minutes from Dublin airport and approximately 3 miles from the beach. ', '122.jpg', 'forsale.png', '2013-01-06 20:47:02'),
(141, '10 Burton Hall', 'Tullyallen', 'Drogheda', 'Louth', 140000, '3', 'Semi-Detached', 'John Little ', '041 6857637', '3 bedroom semi detached house located in small development of just 16 homes located in center of Tullyallen village. Tullyallen is located approx. 3 miles north west of Drogheda. A small vibrant village with all amenities at your door step including primary school, playground, shops and sports ground. M.1 motorway is just a short drive allowing for fast commute to Dublin city.', '123.jpg', 'forsale.png', '2013-01-06 20:49:40'),
(142, 'Currykirwan', 'Mayo Abbey', 'Claremorris', 'Mayo', 135000, '2', 'Detached', 'Colm Casey', '094 9362733', 'Externally, the white walls and beautiful, neat thatch as well as the white walls and red doors of the rear out-buildings make this property visually stunning, which is greatly enhanced by the beautifully manicured and maintained gardens. With its gable to the road, the property is not just beautiful - the orientation of the house presents the gable to the prevailing wind and rain, showing the wisdom in the design. ', '124.png', 'forsale.png', '2013-01-07 12:47:53'),
(143, 'Main Street', 'Hollymount', 'Mayo', 'Mayo', 155000, '2', 'Terraced', 'John Walsh', '087 5236678', 'Beautiful, fully renovated end terrace house located in the quaint village of Hollymount, which is located between the two largest towns in the south of the county Ballinrobe and Claremorris. Close to the lake districts of Lough Corrib and Lough Mask. Galway is less than an hours drive. Village has all the necessary amenities i.e. shop, post office, petrol station, 3 pubs. Local national school and Roman Catholic church approx 2km distance.', '125.jpg', 'forsale.png', '2013-01-07 12:55:45'),
(144, '4', 'Station Road', 'Balla', 'Mayo', 95000, '3', 'Terraced', 'John Walsh', '087 5236678', 'Three bedroomed semi-detached dormer style house in excellent location at Station Road, Balla. All the facilities of the town are within easy reach and the local primary school is only a stroll away. The busy County Capital is only a fifteen minute drive. The house requires a little modernisation but is keenly priced to appeal to a first time buyer.', '126.jpg', 'forsale.png', '2013-01-07 12:57:50'),
(145, '15', 'New Inn', 'Enfield', 'Meath', 235000, '4', 'Detached', 'Edward Carey', '087 5236678', '4 BED DETACHED DORMER BUNGALOW SITUATED IN A MATURE DEVELOPMENT WITHIN WALKING DISTANCE OF BOTH BUS &amp; RAIL STATION. SOME OF THE FEATURES INCLUDED COBBLE LOCK DRIVE, LARGE REAR GARDEN, PATIO AREA, MEZZANINE &amp; 2 EN-SUITE BEDROOMS ', '127.jpg', 'forsale.png', '2013-01-07 13:01:23'),
(146, 'Moate Hill Manor', 'Athboy Road', 'Navan', 'Meath', 70000, '2', 'Apartment', 'Ciara', '087 5236678', 'Clement Herron Real Estate are delighted to introduce to the market this ground floor two bed apartment on the Athboy Road in Navan. ', '128.jpg', 'forsale.png', '2013-01-07 13:02:58'),
(147, '20 Beech Lawn', 'Johnstown Wood', 'Navan', 'Meath', 130000, '3', 'Semi-Detached', 'Ciara', '087 5236678', 'A prime location where the property is not directly overlooked from the front or the rear. This residence benefits from a long driveway to the front providing an abundance of room for parking. There is a large space to the side which had planning permission for a two storey extension. This property provides well proportioned accommodation. ', '129.jpg', 'forsale.png', '2013-01-07 13:04:32');
